version: 2.1

workflows:
  build:
    jobs:
      - build:
          context:
            - circleci-user

jobs:
  build:
    docker:
      - image: 218546966473.dkr.ecr.us-east-1.amazonaws.com/sources-python:1.1.0
    steps:
      - checkout
      - run:
          name: 'Setup virtualenv'
          command: |
            pyenv global 3.11.7
            python3 -m venv ~/.virtualenvs/singer-python
            source ~/.virtualenvs/singer-python/bin/activate
            pip install -U 'pip<20.3.4' 'setuptools<51.0.0'
            make install
      - run:
          name: 'Run tests'
          command: |
            source ~/.virtualenvs/singer-python/bin/activate
            make test
